source 'https://github.com/SourceChang/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '8.0'


target 'MaoTestApp' do

    
  pod 'MapWrapperFramework'
  pod 'MapWrapperFrameworkSwift'

  
end

